#!/bin/bash
TARGET_FILE=$0
CURRENT_DIR=`pwd -P`

cd `dirname $TARGET_FILE`
TARGET_FILE=`basename $TARGET_FILE`
# Iterate down a (possible) chain of symlinks
while [ -L "$TARGET_FILE" ]
do
    TARGET_FILE=`readlink $TARGET_FILE`
    cd `dirname $TARGET_FILE`
    TARGET_FILE=`basename $TARGET_FILE`
done
# Compute the canonicalized name by finding the physical path 
# for the directory we're in and appending the target file.
PHYS_DIR=`pwd -P`
cd $CURRENT_DIR

if [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
  # Do something under GNU/Linux platform
  python3.8 ${PHYS_DIR}/gii_bin.py $@

elif [ "$(uname)" == "Darwin" ]; then
	"${PHYS_DIR}/support/osx/Gii.app/Contents/MacOS/Python3" ${PHYS_DIR}/gii_bin.py $@
fi

