"""
This is a setup.py script generated by py2applet

Usage:
		python setup.py py2app
"""

from setuptools import setup
##----------------------------------------------------------------##

APP_NAME = 'Gii'
AUTHOR   = 'Tommo Zhou'
APP = [ 'gii_bin.py' ]
DATA_FILES = []
OPTIONS = {
	'arch': 'x86_64',
	'argv_emulation': True,
	'optimize': 2,
	'strip': False,
	'semi_standalone' : True,
	'use_pythonpath'  : True,
	'emulate_shell_environment' : True,
	'includes': [ 
		'sip',
		'qtpy',
		'qtpy._qt',
		'qtpy.QtCore',
		'qtpy.QtWidgets',
		'PIL',
		'Pillow',
		'weakref',
		'Queue'
	],

	# 'excludes': [
	# 	'wx',
	# 	'qtpy.QtDesigner',
	# 	'qtpy.QtNetwork',
	# 	'qtpy.QtScript',
	# 	'qtpy.QtSql',
	# 	'qtpy.QtTest',
	# 	'qtpy.QtXml',
	# 	'qtpy.phonon'
	#  ],

	}

setup(
		name           = APP_NAME,
		author         = AUTHOR,
		app            = APP,

		data_files     = DATA_FILES,
		options        = {'py2app': OPTIONS},
		setup_requires = ['py2app']

		# plist = dict(
		# 	CFBundleIdentifier = 'com.hatrix.gii'
		# 	)
)
