def options( opt ):	
	opt.load( 'compiler_cxx compiler_c' )
	opt.load( 'python' )
	opt.load( 'cython' )

def configure( conf ):
	env = conf.env
	conf.load( 'compiler_cxx compiler_c' )
	conf.load( 'python' )
	conf.load( 'cython' )
	conf.env.ARCH  = [ 'i386', 'x86_64' ]

def build( bld ):
	buildTarget = bld.env.TARGET
	if buildTarget == 'html5':
		return
	
	import sys		

	if buildTarget == 'python':
		binPath = bld.env.GII_BINARY_PATH
		import os.path
		if not os.path.exists( binPath + '/python' ):
			os.mkdir( binPath + '/python' )
		output = binPath + '/python'

		if sys.platform == 'darwin':
			source = [ 'freejoy.pyx', 'freejoy.macosx.c' ]
			INSTALL_NAME = 'freejoy.so'
		elif sys.platform == 'win32':
			source = [ 'freejoy.pyx', 'freejoy.win32.c' ]
			INSTALL_NAME = 'freejoy.dll'

		bld(
			source   = 'freejoy.pyx freejoy.macosx.c',
			features = 'cxx cxxshlib pyext',
			target   = INSTALL_NAME,
			name     = 'freejoy',
			includes = [ '.', findPythonInclude() ],

			framework = [ 
				'IOKit' 
			],

			cxxflags = [ '-fvisibility=default' ],

			linkflags = [
				'-L/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config'
			],

			install_path = output
		)
	else:
		
		if sys.platform == 'darwin':
			source = [ 'freejoyWrapper.cpp', 'freejoy.macosx.c' ]
		elif sys.platform == 'win32':
			source = [ 'freejoyWrapper.cpp', 'freejoy.win32.c' ]

		bld.stlib( 
			source = source,
			target = 'freejoy',
			export_includes = '.',	
			includes = [ '.' ],
			cxxflags = [ '-mmacosx-version-min=10.5', '-fvisibility=default' ],
			framework = [ 
				'IOKit' 
			]
		)

def findPythonInclude():
	return '/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7'

