def build( bld ):	
	bld.stlib( 
		features = 'c cxx',
		source   = bld.path.ant_glob( '*.cpp' ),
		target   = 'clipper',
		includes = '.',
		export_includes = '.',
		cxxflags = [ '-stdlib=libstdc++' ]
	)


	