import moai_env
import sys

TARGET_NAME  = 'python'
INSTALL_NAME = 'AKU.so'

def options( opt ):
	opt.load( 'compiler_cxx compiler_c' )
	opt.load( 'python' )
	opt.load( 'cython' )
	
def configure( conf ):
	if sys.platform == 'darwin':
		MOAITargetName = 'osx'
	elif sys.platform == 'win32':
		MOAITargetName = 'win'
	else:
		conf.fatal( 'unknown moai target for current platform' ) 

	for config in [ 'release', 'debug' ]:
		name = '%s-%s' % ( TARGET_NAME, config )
		conf.setenv( name )
		moai_env.setup_moai_env( conf, MOAITargetName, config )
		moai_env.setup_fmod_env( conf, MOAITargetName, config )
		conf.load( 'compiler_cxx compiler_c' )
		conf.load( 'python' )
		conf.load( 'cython' )

def build( bld ):		
	binPath = bld.env.GII_BINARY_PATH
	import os.path
	if not os.path.exists( binPath + '/python' ):
		os.mkdir( binPath + '/python' )
	output = binPath + '/python'

	#build aku-cython	
	LIBS_SYSTEM = [ 'System', 'crypto', 'ssl', 'objc', 'stdc++' ]

	bld(
		source   = 'AKU.pyx GIIHelper.cpp helpers.cpp',
		features = 'cxx cxxshlib pyext',
		target   = INSTALL_NAME,
		name     = 'host-python',
		use      = 'MOAI FMOD modules extension LUA',

		includes = [ '../extension', findPythonInclude() ],

		framework = [ 
			'CoreServices',
			'CoreFoundation',
			'Foundation',
			'AudioUnit',
			'AudioToolbox',
			'GLUT',
			'IOKit',
			'OpenGL',
		],

		stlib      = LIBS_SYSTEM + [ 'python2.7' ],
		cxxflags   = [ 
			'-DMOAI_WITH_LUAEXT', 
			'-DMOAI_WITH_FMOD_DESIGNER',
			'-fvisibility=default'
		],

		linkflags = [
			'-L/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config'
		],

		install_path = output
	)

def findPythonInclude():
	return '/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7'
