<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>bt_script</string>
	</array>
	<key>name</key>
	<string>BT Script</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>//.*$</string>
			<key>name</key>
			<string>comment.line.bt_script</string>
		</dict>
		<dict>
			<key>match</key>
			<string>:(forever|for|repeat|while|not|fail|pass|ok|prob|weight)\s*</string>
			<key>name</key>
			<string>support.decorator.bt_script</string>
		</dict>
		<dict>
			<key>match</key>
			<string>@\s*\w*</string>
			<key>name</key>
			<string>variable.action.bt_script</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(##)\s*(.*)</string>
			<key>name</key>
			<string>string.node_log.bt_script</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*\.\s*(.*)</string>
			<key>name</key>
			<string>constant.node_ref.bt_script</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.sub_def.bt_script</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.sub_name.bt_script</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(sub)\s+(\w+)</string>
			<key>name</key>
			<string>keyword.node_def.bt_script</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\$)\s*([\w.]+)</string>
			<key>name</key>
			<string>string.node_message.bt_script</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.node_value.bt_script</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.node_type.bt_script</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\?|!)\s*(\w+)</string>
			<key>name</key>
			<string>keyword.node_condition.bt_script</string>
		</dict>
		<dict>
			<key>match</key>
			<string>([.=()])</string>
			<key>name</key>
			<string>keyword.operator.bt_script</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.node_value.bt_script</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment.node_type.bt_script</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\|[&amp;~|]|>|\+|~>?)\s*(\w*)</string>
			<key>name</key>
			<string>keyword.node_type.bt_script</string>
		</dict>
	</array>
	
	<key>scopeName</key>
	<string>source.bt_script</string>
	<key>uuid</key>
	<string>91a1cdc0-1572-41ec-982f-bdf5f2cf6181</string>
</dict>
</plist>
